Table accounts {
  age int [check: `age > 0`]
//         ^ property
//                ^ string.special

  checks {
// ^ keyword
    `balance >= 0` [name: 'positive']
//  ^ string.special
//                   ^ property
//                        ^ string
  }
}
